### PR TITLE
Support for HTTPS and various minor fixes/improvements

### PR DESCRIPTION
**Pull request by adepretis**

### CODE REVIEW

**Comment by adepretis** [comment]
any feedback on this @glensc ?

**Comment by glensc** [comment]
should not add another mode, but let http mode also support https urls

**Comment by glensc** [comment]
also i recall that should not add single quotes in template because cacti did that itself. do you have actual error or you just assumed it needs to be escaped?

**Comment by adepretis** [comment]
I do have exactly this version running for a long time and it works

**Comment by glensc** [comment]
also don't like disabling ssl verify by default. makes whole ssl security pointless. install your certs system wise.

**Comment by glensc** [comment]
is there particular reason why new mode is better than using existing mode with just https support added?

**Comment by glensc** [comment]
i guess one can cleanup later using existing mode=http if they really want; merging.

thanks.

**Pull request merged**
